In [1]:
import pandas as pd
import csv
import json

In [70]:
# 데이터 불러오기
df = pd.read_csv('행정_법정동 중심좌표 최종 csv.csv', encoding='euc-kr')
df

         법정동코드     시도  시군구   읍면동  하위         위도          경도 코드종류
0   2911052500  광주광역시   동구   충장동 NaN  35.149211  126.917783    H
1   2911054500  광주광역시   동구   동명동 NaN  35.150568  126.925425    H
2   2911056000  광주광역시   동구  계림1동 NaN  35.158538  126.919569    H
3   2911057000  광주광역시   동구  계림2동 NaN  35.158130  126.923383    H
4   2911059000  광주광역시   동구  산수1동 NaN  35.157330  126.930703    H
..         ...    ...  ...   ...  ..        ...         ...  ...
90  2920066000  광주광역시  광산구   동곡동 NaN  35.098697  126.772108    H
91  2920067000  광주광역시  광산구    평동 NaN  35.124653  126.760276    H
92  2920068000  광주광역시  광산구   삼도동 NaN  35.128304  126.691671    H
93  2920069000  광주광역시  광산구   본량동 NaN  35.180771  126.728816    H
94  2920070000  광주광역시  광산구   신창동 NaN  35.190432  126.846612    H

[95 rows x 8 columns]

In [71]:
df.drop(['하위'], axis=1)

         법정동코드     시도  시군구   읍면동         위도          경도 코드종류
0   2911052500  광주광역시   동구   충장동  35.149211  126.917783    H
1   2911054500  광주광역시   동구   동명동  35.150568  126.925425    H
2   2911056000  광주광역시   동구  계림1동  35.158538  126.919569    H
3   2911057000  광주광역시   동구  계림2동  35.158130  126.923383    H
4   2911059000  광주광역시   동구  산수1동  35.157330  126.930703    H
..         ...    ...  ...   ...        ...         ...  ...
90  2920066000  광주광역시  광산구   동곡동  35.098697  126.772108    H
91  2920067000  광주광역시  광산구    평동  35.124653  126.760276    H
92  2920068000  광주광역시  광산구   삼도동  35.128304  126.691671    H
93  2920069000  광주광역시  광산구   본량동  35.180771  126.728816    H
94  2920070000  광주광역시  광산구   신창동  35.190432  126.846612    H

[95 rows x 7 columns]

In [73]:
# 데이터프레임화
df2 = pd.DataFrame(df, columns=['법정동코드', '시군구', '읍면동', '위도', '경도'])
df2

         법정동코드  시군구   읍면동         위도          경도
0   2911052500   동구   충장동  35.149211  126.917783
1   2911054500   동구   동명동  35.150568  126.925425
2   2911056000   동구  계림1동  35.158538  126.919569
3   2911057000   동구  계림2동  35.158130  126.923383
4   2911059000   동구  산수1동  35.157330  126.930703
..         ...  ...   ...        ...         ...
90  2920066000  광산구   동곡동  35.098697  126.772108
91  2920067000  광산구    평동  35.124653  126.760276
92  2920068000  광산구   삼도동  35.128304  126.691671
93  2920069000  광산구   본량동  35.180771  126.728816
94  2920070000  광산구   신창동  35.190432  126.846612

[95 rows x 5 columns]

In [74]:
# 데이터프레임을 JSON 파일로 내보내기
output_file = 'outputFinal2.json'
with open(output_file, 'w', encoding='utf-8') as json_file:
    json_file.write(df2.to_json(orient='records', force_ascii=False, indent=2)) # indent = 줄바꿈 
print('JSON 파일이 생성되었습니다.')

JSON 파일이 생성되었습니다.