In [2]:
import pandas as pd

In [3]:
data= pd.read_csv("./아파트(매매)__실거래가2023년7월.csv", encoding="EUC-KR")

In [11]:
data.head()

             시군구      단지명  전용면적(㎡)    계약년월  계약일 거래금액(만원)   층  건축년도
0  광주광역시 광산구 도산동      대덕1    31.59  202307   27    5,500   8  1990
1  광주광역시 광산구 도산동      대덕1    39.15  202307   28    7,200   7  1990
2  광주광역시 광산구 도산동  대주피오레1차    84.98  202307    5   23,250   4  2000
3  광주광역시 광산구 도산동       서경    59.79  202307   13   14,200  11  1998
4  광주광역시 광산구 도산동       서라    59.31  202307   13   12,300  12  1997

In [6]:
data=data.drop(['번지','본번','부번','도로명','해제사유발생일','거래유형','중개사소재지'], axis=1)

In [10]:
data=data.drop(['등기신청일자'],axis=1)

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1146 entries, 0 to 1145
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   시군구       1146 non-null   object
 1   단지명       1146 non-null   object
 2   전용면적(㎡)   1146 non-null   float64
 3   계약년월      1146 non-null   int64
 4   계약일       1146 non-null   int64
 5   거래금액(만원)  1146 non-null   object
 6   층         1146 non-null   int64
 7   건축년도      1146 non-null   int64
 8   등기신청일자    1146 non-null   object
dtypes: float64(1), int64(4), object(4)
memory usage: 80.7+ KB

In [12]:
# 시군구에서 동명만 추출
data['동명'] = data['시군구'].apply(lambda x: x.split()[-1])

In [13]:
# 거래건수 추가
data['거래건수'] = data.groupby(['시군구', '계약년월'])['시군구'].transform('count')

In [16]:
# 건축나이 추가
data['계약년']=data['계약년월']//100
data['건축나이']= data['계약년']-data['건축년도']

In [39]:
# 금리 추가

data['기준금리'] = 3.5

In [40]:
data

,시군구,단지명,전용면적(㎡),계약년월,계약일,거래금액(만원),층,건축년도,동명,거래건수,계약년,건축나이,기준금리
0,광주광역시 광산구 도산동,대덕1,31.5900,202307,27,"5,500",8,1990,도산동,19,2023,33,3.5
1,광주광역시 광산구 도산동,대덕1,39.1500,202307,28,"7,200",7,1990,도산동,19,2023,33,3.5
2,광주광역시 광산구 도산동,대주피오레1차,84.9800,202307,5,"23,250",4,2000,도산동,19,2023,23,3.5
3,광주광역시 광산구 도산동,서경,59.7900,202307,13,"14,200",11,1998,도산동,19,2023,25,3.5
4,광주광역시 광산구 도산동,서라,59.3100,202307,13,"12,300",12,1997,도산동,19,2023,26,3.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1141,광주광역시 서구 화정동,화정동영무예다음,59.6134,202307,12,"14,300",10,2003,화정동,42,2023,20,3.5
1142,광주광역시 서구 화정동,화정동영무예다음,59.6134,202307,14,"13,600",11,2003,화정동,42,2023,20,3.5
1143,광주광역시 서구 화정동,화정우미,59.8300,202307,6,"16,500",9,1996,화정동,42,2023,27,3.5
1144,광주광역시 서구 화정동,화정우미,59.8300,202307,6,"16,500",9,1996,화정동,42,2023,27,3.5
1145,광주광역시 서구 화정동,화정우미,59.8300,202307,13,"17,000",17,1996,화정동,42,2023,27,3.5

In [11]:
data.head()

,시군구,단지명,전용면적(㎡),계약년월,계약년,계약일,거래금액(만원),층,건축년도,동명,거래건수,건축나이,기준금리
0,광주광역시 광산구 도산동,대덕1,59.3100,202303,2023,18,"9,800",4,1990,도산동,20,33,3.5
1,광주광역시 광산구 도산동,대주피오레1차,84.9800,202302,2023,7,"21,000",2,2000,도산동,14,23,3.5
2,광주광역시 광산구 도산동,대주피오레1차,84.9800,202305,2023,31,"22,350",5,2000,도산동,16,23,3.5
3,광주광역시 광산구 도산동,대주피오레2차,84.7575,202305,2023,9,"22,400",5,2001,도산동,16,22,3.5
4,광주광역시 광산구 도산동,대주피오레2차,84.7575,202305,2023,13,"22,000",13,2001,도산동,16,22,3.5

In [41]:
# 법정명 코드 추가
bub_code=pd.read_csv('법정동코드 조회자료.csv')

In [42]:
bub_code

          법정동코드            법정동명
0    2900000000           광주광역시
1    2911000000        광주광역시 동구
2    2911010100    광주광역시 동구 대인동
3    2911010200  광주광역시 동구 금남로5가
4    2911010300  광주광역시 동구 충장로5가
..          ...             ...
203  2920017500   광주광역시 광산구 동호동
204  2920017600   광주광역시 광산구 덕림동
205  2920017700   광주광역시 광산구 양산동
206  2920017800   광주광역시 광산구 동림동
207  2920020200   광주광역시 광산구 오선동

[208 rows x 2 columns]

In [43]:
data['법정동명']=data['시군구']

In [44]:
data = data.merge(bub_code, on='법정동명', how='left')

In [45]:
data

,시군구,단지명,전용면적(㎡),계약년월,계약일,거래금액(만원),층,건축년도,동명,거래건수,계약년,건축나이,기준금리,법정동명,법정동코드
0,광주광역시 광산구 도산동,대덕1,31.5900,202307,27,"5,500",8,1990,도산동,19,2023,33,3.5,광주광역시 광산구 도산동,2920010200
1,광주광역시 광산구 도산동,대덕1,39.1500,202307,28,"7,200",7,1990,도산동,19,2023,33,3.5,광주광역시 광산구 도산동,2920010200
2,광주광역시 광산구 도산동,대주피오레1차,84.9800,202307,5,"23,250",4,2000,도산동,19,2023,23,3.5,광주광역시 광산구 도산동,2920010200
3,광주광역시 광산구 도산동,서경,59.7900,202307,13,"14,200",11,1998,도산동,19,2023,25,3.5,광주광역시 광산구 도산동,2920010200
4,광주광역시 광산구 도산동,서라,59.3100,202307,13,"12,300",12,1997,도산동,19,2023,26,3.5,광주광역시 광산구 도산동,2920010200
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1141,광주광역시 서구 화정동,화정동영무예다음,59.6134,202307,12,"14,300",10,2003,화정동,42,2023,20,3.5,광주광역시 서구 화정동,2914011900
1142,광주광역시 서구 화정동,화정동영무예다음,59.6134,202307,14,"13,600",11,2003,화정동,42,2023,20,3.5,광주광역시 서구 화정동,2914011900
1143,광주광역시 서구 화정동,화정우미,59.8300,202307,6,"16,500",9,1996,화정동,42,2023,27,3.5,광주광역시 서구 화정동,2914011900
1144,광주광역시 서구 화정동,화정우미,59.8300,202307,6,"16,500",9,1996,화정동,42,2023,27,3.5,광주광역시 서구 화정동,2914011900
1145,광주광역시 서구 화정동,화정우미,59.8300,202307,13,"17,000",17,1996,화정동,42,2023,27,3.5,광주광역시 서구 화정동,2914011900

In [46]:
data=data.drop(['법정동명','건축년도'],axis=1)

In [47]:
data

,시군구,단지명,전용면적(㎡),계약년월,계약일,거래금액(만원),층,동명,거래건수,계약년,건축나이,기준금리,법정동코드
0,광주광역시 광산구 도산동,대덕1,31.5900,202307,27,"5,500",8,도산동,19,2023,33,3.5,2920010200
1,광주광역시 광산구 도산동,대덕1,39.1500,202307,28,"7,200",7,도산동,19,2023,33,3.5,2920010200
2,광주광역시 광산구 도산동,대주피오레1차,84.9800,202307,5,"23,250",4,도산동,19,2023,23,3.5,2920010200
3,광주광역시 광산구 도산동,서경,59.7900,202307,13,"14,200",11,도산동,19,2023,25,3.5,2920010200
4,광주광역시 광산구 도산동,서라,59.3100,202307,13,"12,300",12,도산동,19,2023,26,3.5,2920010200
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1141,광주광역시 서구 화정동,화정동영무예다음,59.6134,202307,12,"14,300",10,화정동,42,2023,20,3.5,2914011900
1142,광주광역시 서구 화정동,화정동영무예다음,59.6134,202307,14,"13,600",11,화정동,42,2023,20,3.5,2914011900
1143,광주광역시 서구 화정동,화정우미,59.8300,202307,6,"16,500",9,화정동,42,2023,27,3.5,2914011900
1144,광주광역시 서구 화정동,화정우미,59.8300,202307,6,"16,500",9,화정동,42,2023,27,3.5,2914011900
1145,광주광역시 서구 화정동,화정우미,59.8300,202307,13,"17,000",17,화정동,42,2023,27,3.5,2914011900

In [48]:
# 동별 지하철 갯수 추가
subway_count_data=pd.read_csv('동별 역갯수.csv', encoding="EUC-KR")

In [49]:
subway_count_data

       동명  지하철역수
0     광산동      1
1   금남로4가      1
2   금남로5가      1
3     농성동      2
4     도산동      1
5     마륵동      2
6     소태동      1
7     송정동      2
8     신촌동      1
9     쌍촌동      2
10     양동      1
11    용산동      1
12    월전동      1
13     학동      2
14    화정동      1

In [50]:
data=data.merge(subway_count_data, on="동명",how='left' )

In [51]:
data['지하철역수'].fillna(0, inplace=True)

In [52]:
data['지하철역수']

0       1.0
1       1.0
2       1.0
3       1.0
4       1.0
       ...
1141    1.0
1142    1.0
1143    1.0
1144    1.0
1145    1.0
Name: 지하철역수, Length: 1146, dtype: float64

In [53]:
data['지하철역수'] = data['지하철역수'].astype(int)

In [54]:
column_order = ['시군구', '단지명', '전용면적(㎡)', '계약년월', '계약년', '계약일','계약날짜', '층', '건축나이', '거래건수', '기준금리', '법정동코드', '동명', '지하철역수', '거래금액(만원)']
data =data.reindex(columns=column_order)

In [55]:
data=data.drop(['계약년','동명'], axis=1)

In [57]:
data['계약날짜'] = pd.to_datetime(data['계약년월'].astype(str) + data['계약일'].astype(str), format='%Y%m%d')

In [58]:
data

,시군구,단지명,전용면적(㎡),계약년월,계약일,계약날짜,층,건축나이,거래건수,기준금리,법정동코드,지하철역수,거래금액(만원)
0,광주광역시 광산구 도산동,대덕1,31.5900,202307,27,2023-07-27,8,33,19,3.5,2920010200,1,"5,500"
1,광주광역시 광산구 도산동,대덕1,39.1500,202307,28,2023-07-28,7,33,19,3.5,2920010200,1,"7,200"
2,광주광역시 광산구 도산동,대주피오레1차,84.9800,202307,5,2023-07-05,4,23,19,3.5,2920010200,1,"23,250"
3,광주광역시 광산구 도산동,서경,59.7900,202307,13,2023-07-13,11,25,19,3.5,2920010200,1,"14,200"
4,광주광역시 광산구 도산동,서라,59.3100,202307,13,2023-07-13,12,26,19,3.5,2920010200,1,"12,300"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1141,광주광역시 서구 화정동,화정동영무예다음,59.6134,202307,12,2023-07-12,10,20,42,3.5,2914011900,1,"14,300"
1142,광주광역시 서구 화정동,화정동영무예다음,59.6134,202307,14,2023-07-14,11,20,42,3.5,2914011900,1,"13,600"
1143,광주광역시 서구 화정동,화정우미,59.8300,202307,6,2023-07-06,9,27,42,3.5,2914011900,1,"16,500"
1144,광주광역시 서구 화정동,화정우미,59.8300,202307,6,2023-07-06,9,27,42,3.5,2914011900,1,"16,500"
1145,광주광역시 서구 화정동,화정우미,59.8300,202307,13,2023-07-13,17,27,42,3.5,2914011900,1,"17,000"

In [ ]:
data.

In [59]:
data.to_csv('7월 테스트 데이터.csv', encoding='EUC-KR',index=False)